services:
  
  db:
    image: mongo
    restart: always
    volumes:
      - /var/lib/db


  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports:
      - 8081:8081
    environment:
      - DB_SERVER=db
      - forum_secret_key=placeholder
    
