services:
  
  db:
    image: mongo
    restart: always
    volumes:
      - /var/lib/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker

  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports:
      - 8081:8081
    environment:
      - DB_SERVER=db
    
